import express from "express";

// Get bearer token from environment variable
// This token is generated by Kindred when you register your agent
const TOKEN = process.env.KINDRED_BEARER_TOKEN ?? "";

if (!TOKEN) {
  console.warn("WARNING: KINDRED_BEARER_TOKEN not set. Set it to the token provided by Kindred when registering your agent.");
}

const app = express();
app.use(express.raw({ type: "*/*" }));

function checkAuth(req) {
  /** Verify the request is from Kindred using the bearer token. */
  const authHeader = req.headers["authorization"] ?? "";
  const expected = `Bearer ${TOKEN}`;
  return authHeader === expected;
}

app.post("/run_step", (req, res) => {
  // Verify authentication
  if (!checkAuth(req)) {
    res.status(401).json({ error: "unauthorized" });
    return;
  }

  try {
    const payload = JSON.parse(req.body.toString("utf8"));
    const tool = payload.tools?.[0]?.name ?? "say";
    const args = tool === "say" ? { message: "ok" } : {};
    res.json({
      thought: "Choosing a safe default action.",
      action: { tool, args }
    });
  } catch (err) {
    res.status(400).json({ error: String(err) });
  }
});

app.listen(3001, () => console.log("agent running on :3001"));
