import json
import os
from typing import Any, Dict

from fastapi import FastAPI, HTTPException, Request

app = FastAPI()

# Get bearer token from environment variable
# This token is generated by Kindred when you register your agent
TOKEN = os.getenv("KINDRED_BEARER_TOKEN", "")

if not TOKEN:
    print("WARNING: KINDRED_BEARER_TOKEN not set. Set it to the token provided by Kindred when registering your agent.")


def _check_auth(req: Request) -> bool:
    """Verify the request is from Kindred using the bearer token."""
    auth_header = req.headers.get("authorization", "")
    expected = f"Bearer {TOKEN}"
    return auth_header == expected


def _pick_tool(tools: Any) -> str:
    if isinstance(tools, list) and tools:
        first = tools[0]
        if isinstance(first, dict) and "name" in first:
            return str(first["name"])
    return "say"


def _safe_args(tool: str) -> Dict[str, Any]:
    if tool == "say":
        return {"message": "ok"}
    return {}


@app.post("/run_step")
async def run_step(req: Request):
    # Verify authentication
    if not _check_auth(req):
        raise HTTPException(401, "unauthorized")

    # Parse request body
    raw = await req.body()
    payload = json.loads(raw.decode("utf-8"))
    
    # Simple agent logic: use the first available tool
    tool = _pick_tool(payload.get("tools"))
    args = _safe_args(tool)
    
    return {
        "thought": "Choosing a safe default action.",
        "action": {"tool": tool, "args": args},
    }
